image: python:3.6-slim

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - echo "build python package"
    - python setup.py sdist

test:
  stage: test
  script:
    - echo "test installing python package in ubuntu container"

deploy_staging:
  stage: deploy
  variables:
    TWINE_USERNAME: $STAGING_USERNAME
    TWINE_PASSWORD: $STAGING_PASSWORD
  environment:
    name: staging
    url: $PYPRI_REPOSITORY_URL
  script:
    - echo "deploy python package to staging server"
    - python setup.py sdist
    - pip install twine
    - twine upload --repository-url $PYPRI_REPOSITORY_URL dist/*
  except:
    - tags

deploy_production:
  stage: deploy
  variables:
    TWINE_USERNAME: $PRODUCTION_USERNAME
    TWINE_PASSWORD: $PRODUCTION_PASSWORD
  environment:
    name: production
    url: https://pypi.org/project/starid/
  script:
    - echo "deploy python package to production server"
    - python setup.py sdist
    - pip install twine
    - twine upload dist/*
  only:
    - tags
