image: ubuntu:latest

stages:
  - build
  - test
  - deploy

before_script:
  - apt-get -qq -update
  - apt-get -qq install -y python python-virtualenv python-pip
  - virtualenv venv
  - . venv/bin/activate

build:
  stage: build
  artifacts:
    paths:
      - dist/
  script:
    - python setup.py sdist

test:
  stage: test
  dependencies:
    - build
  script:
    - echo "test installing python package in ubuntu container"

deploy_staging:
  stage: deploy
  variables:
    TWINE_USERNAME: $STAGING_USERNAME
    TWINE_PASSWORD: $STAGING_PASSWORD
  environment:
    name: staging
    url: $PYPRI_REPOSITORY_URL
  dependencies:
    - build
  only:
    - master
  except:
    - tags
  script:
    - pip install twine
    - twine upload --repository-url $PYPRI_REPOSITORY_URL dist/*

deploy_production:
  stage: deploy
  variables:
    TWINE_USERNAME: $PRODUCTION_USERNAME
    TWINE_PASSWORD: $PRODUCTION_PASSWORD
  environment:
    name: production
    url: https://pypi.org/project/starid/
  dependencies:
    - build
  only:
    - tags
  except:
    - branches
  script:
    - pip install twine
    - twine upload dist/*

