image: ubuntu:focal

stages:
  - build
  - deploy

build:
  stage: build
  artifacts:
    paths:
      - dist/
  script:
    - echo "build"

deploy_staging:
  stage: deploy
  variables:
    TWINE_USERNAME: $STAGING_USERNAME
    TWINE_PASSWORD: $STAGING_PASSWORD
  environment:
    name: staging
    url: $TESTPYPI_URL
  dependencies:
    - build
  only:
    - master
  except:
    - tags
  script:
    - echo "deploy staging"
#    - pip install twine
#    - twine upload --repository-url $TESTPYPI_URL dist/*

deploy_production:
  stage: deploy
  variables:
    TWINE_USERNAME: $PRODUCTION_USERNAME
    TWINE_PASSWORD: $PRODUCTION_PASSWORD
  environment:
    name: production
    url: https://pypi.org/project/starid/
  dependencies:
    - build
  only:
    - tags
  except:
    - branches
  script:
    - echo "deploy production"
#    - pip install twine
#    - twine upload dist/*

