plugins:
  - jekyll-feed
title: statespace.dev
description: explorations
author:
  name: noah smith
  email: noah@statespace.dev
google_analytics: G-W7B7DSQKFD
remote_theme: jekyll/minima
minima:
  skin: dark
  nav_pages:
    - docs/about.md
    - docs/photos.md
header_pages:
  - docs/about.md
  - docs/photos.md
include:
  - .well-known
exclude: ['data', 'docs/images', 'docs/images2', 'docs/papers', 'docs/archives', 'docs/inverse', 'docs/data_commandeur_koopman', 'docs/data_durbin_koopman', 'docs/la01', 'docs/la04', 'docs/toolbox_grewal_andrews', 'docs/toolbox_merwe', 'decwar', 'dec10', 'ibm7094']
show_drafts: false
permalink: none
