plugins:
  - jekyll-feed
title: statespace.dev
description: explorations
author:
  name: noah smith
  email: noah@statespace.dev
google_analytics: G-W7B7DSQKFD
remote_theme: jekyll/minima
minima:
  skin: dark
  nav_pages:
    - docs/about.md
    - docs/photos.md
header_pages:
  - docs/about.md
  - docs/photos.md
include:
  - .well-known
show_drafts: false
permalink: none
