plugins:
  - jekyll-feed
title: state space dev | starid
description: star identification, state space models
author:
  name: noah smith
  email: noah@statespace.dev
remote_theme: jekyll/minima
minima:
  skin: dark
  social_links:
    - {platform: github, user_url: "https://github.com/statespacedev/starid"}
    - {platform: linkedin, user_url: "https://www.linkedin.com/in/noahhsmith/"}
header_pages:
  - docs/about.md
  - docs/photos.md
