plugins:
  - jekyll-feed
title: statespace.dev
description: night sky, kalman, particle
author:
  name: noah smith
  email: noah@statespace.dev
google_analytics: G-W7B7DSQKFD
remote_theme: jekyll/minima
minima:
  skin: dark
  social_links:
    - {platform: github, user_url: "https://github.com/statespacedev/starid"}
    - {platform: linkedin, user_url: "https://www.linkedin.com/in/noahhsmith/"}
header_pages:
  - docs/about.md
  - docs/photos.md
show_drafts: false
