#!/bin/bash

source=../algebra/algebra.for

echo "\$job           job1" > job
echo "\$execute       ibjob" >> job
echo "\$ibjob         map" >> job
echo "\$ibftc deck1   list,dd,nodeck,m94" >> job
cat $source >> job
echo "~" >> job
echo "\$ibsys" >> job
echo "\$stop" >> job
sed -i -e 's/nout = 6/nout = 7/g' job

./mkbcdtape -o job.tp -b1 -r84 job

./i7090 runner.ini | tr -d '\r' | grep -E -v '^$|SIM-INFO'

./listtape sysou1.tp | grep -E -v 'to big'

./listtape -a sysou2.tp | grep -E -v '0000000|to big'
