#!/bin/bash

source=../algebra/algebra.for
# source=../inverse/inverse.for

cat $source > job
sed -i -e 's/c\$/\$/g' job
sed -i -e 's/c~/~/g' job
sed -i -e 's/nout = 6/nout = 7/g' job
sed -i -e 's/write (nout/write (7/g' job

rm job.tp
rm sys*
./mkbcdtape -o job.tp -b1 -r84 job

./ibm7094 runner.ini | tr -d '\r' | grep -E -v '^$|SIM-INFO'

#./listtape sysou1.tp

./listtape -a syspp1.tp | grep '^OUT'
