# CMake generated Testfile for 
# Source directory: /home/noah/starid/libstarid/cereal-1.2.2/unittests
# Build directory: /home/noah/starid/libstarid/cereal-1.2.2/unittests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(portability_test "/home/noah/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/182.3911.40/bin/cmake/linux/bin/cmake" "-DPORTABILITY_TEST_DIR=/home/noah/starid/libstarid/cereal-1.2.2/unittests" "-P" "/home/noah/starid/libstarid/cereal-1.2.2/unittests/run_portability_test.cmake")
add_test(test_array "test_array")
add_test(test_array_32 "test_array_32")
add_test(test_basic_string "test_basic_string")
add_test(test_basic_string_32 "test_basic_string_32")
add_test(test_bitset "test_bitset")
add_test(test_bitset_32 "test_bitset_32")
add_test(test_boost_variant "test_boost_variant")
add_test(test_boost_variant_32 "test_boost_variant_32")
add_test(test_chrono "test_chrono")
add_test(test_chrono_32 "test_chrono_32")
add_test(test_complex "test_complex")
add_test(test_complex_32 "test_complex_32")
add_test(test_deque "test_deque")
add_test(test_deque_32 "test_deque_32")
add_test(test_forward_list "test_forward_list")
add_test(test_forward_list_32 "test_forward_list_32")
add_test(test_list "test_list")
add_test(test_list_32 "test_list_32")
add_test(test_load_construct "test_load_construct")
add_test(test_load_construct_32 "test_load_construct_32")
add_test(test_map "test_map")
add_test(test_map_32 "test_map_32")
add_test(test_memory "test_memory")
add_test(test_memory_32 "test_memory_32")
add_test(test_memory_cycles "test_memory_cycles")
add_test(test_memory_cycles_32 "test_memory_cycles_32")
add_test(test_multimap "test_multimap")
add_test(test_multimap_32 "test_multimap_32")
add_test(test_multiset "test_multiset")
add_test(test_multiset_32 "test_multiset_32")
add_test(test_pair "test_pair")
add_test(test_pair_32 "test_pair_32")
add_test(test_pod "test_pod")
add_test(test_pod_32 "test_pod_32")
add_test(test_polymorphic "test_polymorphic")
add_test(test_polymorphic_32 "test_polymorphic_32")
add_test(test_portable_binary_archive "test_portable_binary_archive")
add_test(test_portable_binary_archive_32 "test_portable_binary_archive_32")
add_test(test_priority_queue "test_priority_queue")
add_test(test_priority_queue_32 "test_priority_queue_32")
add_test(test_queue "test_queue")
add_test(test_queue_32 "test_queue_32")
add_test(test_set "test_set")
add_test(test_set_32 "test_set_32")
add_test(test_stack "test_stack")
add_test(test_stack_32 "test_stack_32")
add_test(test_structs "test_structs")
add_test(test_structs_32 "test_structs_32")
add_test(test_structs_minimal "test_structs_minimal")
add_test(test_structs_minimal_32 "test_structs_minimal_32")
add_test(test_structs_specialized "test_structs_specialized")
add_test(test_structs_specialized_32 "test_structs_specialized_32")
add_test(test_tuple "test_tuple")
add_test(test_tuple_32 "test_tuple_32")
add_test(test_unordered_loads "test_unordered_loads")
add_test(test_unordered_loads_32 "test_unordered_loads_32")
add_test(test_unordered_map "test_unordered_map")
add_test(test_unordered_map_32 "test_unordered_map_32")
add_test(test_unordered_multimap "test_unordered_multimap")
add_test(test_unordered_multimap_32 "test_unordered_multimap_32")
add_test(test_unordered_multiset "test_unordered_multiset")
add_test(test_unordered_multiset_32 "test_unordered_multiset_32")
add_test(test_unordered_set "test_unordered_set")
add_test(test_unordered_set_32 "test_unordered_set_32")
add_test(test_user_data_adapters "test_user_data_adapters")
add_test(test_user_data_adapters_32 "test_user_data_adapters_32")
add_test(test_valarray "test_valarray")
add_test(test_valarray_32 "test_valarray_32")
add_test(test_vector "test_vector")
add_test(test_vector_32 "test_vector_32")
add_test(test_versioning "test_versioning")
add_test(test_versioning_32 "test_versioning_32")
add_test(test_cmake_config_module "/home/noah/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/182.3911.40/bin/cmake/linux/bin/cmake" "-P" "/home/noah/starid/libstarid/cereal-1.2.2/unittests/cmake-config-module.cmake")
