[project]
name = "agent"
description = "agent for interacting with decwar"
readme = "readme.md"
requires-python = ">=3.9"
dependencies = ["pexpect"]

[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project.optional-dependencies]
