class StartriangleNOMAD:
   '''NOMAD triangle. focus is on the basestar and baseside - nomad is about a chain of basesides, each increasing the constraints on the preceding basestars. first constructor here is for the initial triangle and has the target star as basestar. second constructor is for following triangles. each takes side2 from its predecessor and uses that as its baseside. the chain of triangles is a train of baseides - side2 of each triangle is the baseside of the following triangle. during feedback, these shared side2 -> baseside pairs are the path for information to flow backwards, all the way backward from latest triangle to the initial triangle - increasing the constraints on the initial triangle baseside and basestar.'''
   def constrain(self):
      '''in each of the three sides, there's a pairhalf1 -> pairhalf -> 0 or 1 concept. 0 is the default and means drop this pair. here we will mark pairs to keep by setting them to 1, all others will be dropped.'''
   def feedback(self):
      '''increase the constraints on the baseside in the prev triangle, using the baseside of the following triangle in the chain. as triangles are added, constraints flow backwards through preceding basesides and basestars. the chain of triangles is a train of baseides - side2 of each triangle is the baseside of the following triangle. during feedback, these shared side2 -> baseside pairs are the path for information to flow backwards, all the way backward from latest triangle to the initial triangle - increasing the constraints on the initial triangle baseside and basestar.'''
   def stop(self):
      '''stopping condition. true if basestars and basesides have been constrained to the point where only one possible basestar remains.'''
class StartriangleSETTLER:
   '''SETTLER triangle. acts as the triangles abca and abda within the star triangle identifier inner loops. their are three triangle sides - representing three star pairs, each with an angular separation. each side is acted by a star triangle side object. star recognition focused on triangles that contain the target star - star a is always the target star, star b is a neighbor star, and an abside is a star pair and triangle side with the target as the first member of the pair. in the inner loops, additional stars c and d are involved. first an abca triangle is formed. this constrains the abside. then for an abca triangle, a sequence of abda triangles are formed, further constraining the abside. when we reach an abda that eliminates all but one star pair possibility for the abside, we've recognized the target star. until that happens, we continue picking new absides, with new abca triangles, with new abda triangles. the name SETTLER comes from the idea that we never move away the target star, we're settling around it.'''
   def constrain_abda(self, triangles):
      '''test candidate star pairs for the sides of an abda triangle.'''
   def constrain_abca(self):
      '''test candidate star pairs for the sides of an abca triangle.'''
